INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (57, 'Alemanha', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (26, 'Argentina', 4);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (59, 'Bélgica', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (23, 'Canadá', 3);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (28, 'Chile', 4);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (62, 'Dinamarca', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (63, 'Eslováquia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (65, 'Espanha', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (24, 'Estados Unidos', 3);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (68, 'França', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (70, 'Holanda', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (72, 'Irlanda', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (73, 'Itália', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (74, 'Letônia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (25, 'México', 3);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (33, 'Paraguai', 4);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (78, 'Polônia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (79, 'Portugal', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (80, 'Reino Unido', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (83, 'Rússia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (85, 'Suécia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (86, 'Suíça', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (88, 'Ucrânia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (37, 'Venezuela', 4);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (2, 'Angola', 1);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (90, 'Austrália', 7);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (22, 'Outros América Central e Caribe', 2);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (40, 'China', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (29, 'Colômbia', 4);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (12, 'Costa Rica', 2);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (14, 'El Salvador', 2);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (30, 'Equador', 4);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (43, 'Filipinas', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (69, 'Grécia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (15, 'Guatemala', 2);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (31, 'Guiana', 4);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (17, 'Honduras', 2);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (71, 'Hungria', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (44, 'Índia', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (47, 'Israel', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (48, 'Japão', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (50, 'Malásia', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (89, 'Outros países da Europa', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (6, 'Marrocos', 1);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (7, 'Moçambique', 1);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (77, 'Noruega', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (19, 'Panamá', 2);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (51, 'Paquistão', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (34, 'Peru', 4);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (52, 'República da Coreia', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (20, 'República Dominicana', 2);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (81, 'República Tcheca', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (82, 'Romênia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (35, 'Suriname', 4);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (54, 'Tailândia', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (27, 'Bolívia', 4);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (36, 'Uruguai', 4);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (58, 'Áustria', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (60, 'Bulgária', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (3, 'Cabo Verde', 1);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (56, 'Outros países da Ásia', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (61, 'Croácia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (64, 'Eslovênia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (66, 'Estônia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (11, 'Outros países da África', 1);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (75, 'Lituânia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (76, 'Luxemburgo', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (84, 'Sérvia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (87, 'Turquia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (67, 'Finlândia', 6);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (45, 'Indonésia', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (46, 'Irã', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (18, 'Nicarágua', 2);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (9, 'Quênia', 1);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (10, 'Tunísia', 1);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (42, 'Cingapura', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (13, 'Cuba', 2);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (4, 'Egito', 1);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (16, 'Haiti', 2);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (91, 'Nova Zelândia', 7);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (55, 'Taiwan', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (21, 'Trinidad e Tobago', 2);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (1, 'África do Sul', 1);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (38, 'Arábia Saudita', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (49, 'Líbano', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (92, 'Outros países da Oceania', 7);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (5, 'Gana', 1);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (8, 'Nigéria', 1);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (39, 'Bangladesh', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (53, 'Síria', 5);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (93, 'Países não especificados', 8);
INSERT INTO paises (id_pais, nome_pais, id_continente) VALUES (32, 'Guiana Francesa', 4);
